/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author Paul Joel D. Perez <pjdperez@mymail.mapua.edu.ph>
 */

package controller;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import models.SaleTransaction;
import models.Buyer;
import models.User;
import models.Admin;
import models.Agent;

public class ReportGenerator {

    private static String getDynamicFileName(User user, String extension) {
        String name = (user != null) ? user.getFirstName() + "_" + user.getLastName() : "System";
        String role = (user instanceof Admin) ? "Admin" : "Agent";
        return name.replaceAll("\\s+", "_") + "_" + role + "_Report" + extension;
    }

    public static String getDownloadsPath(String fileName) {
        String home = System.getProperty("user.home");
        return home + File.separator + "Downloads" + File.separator + fileName;
    }

    public static String buildReportString(List<SaleTransaction> transactions, User user) {
        String userName = (user != null) ? user.getFirstName() + " " + user.getLastName() : "System";
        String role = (user instanceof Admin) ? "Admin" : "Agent";

        StringBuilder sb = new StringBuilder();
        sb.append("ESTATE SALES REPORT (").append(role.toUpperCase()).append(")\n");
        sb.append("Generated: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("\n");
        sb.append("Generated By: ").append(userName).append(" (ID: ").append(user != null ? user.getId() : 0).append(")\n");
        sb.append("--------------------------------------------------\n");
        
        double totalSales = 0;
        int count = 0;
        for (SaleTransaction t : transactions) {
            boolean isAuthorized = (user instanceof Admin) || (user instanceof Agent && t.getAgentID() == user.getId());

            if (isAuthorized && t.getStatus().equals("Approved")) {
                Buyer buyer = (Buyer) UserManager.getInstance().getUserById(t.getBuyerID(), "Buyer");
                String buyerName = (buyer != null) ? buyer.getFirstName() + " " + buyer.getLastName() : "Unknown Buyer";
                
                Agent agent = (Agent) UserManager.getInstance().getUserById(t.getAgentID(), "Agent");
                String agentName = (agent != null) ? agent.getFirstName() + " " + agent.getLastName() : "Unknown Agent";

                // Appended Agent details
                sb.append(String.format("Trans ID: %d | Lot: %d | Agent: %s (ID: %d) | Buyer: %s (ID: %d) | %s | PHP %,.2f\n", 
                        t.getTransactionID(), t.getLotID(), agentName, t.getAgentID(), buyerName, t.getBuyerID(), t.getFinancingType(), t.getAmount()));
                totalSales += t.getAmount();
                count++;
            }
        }
        sb.append("--------------------------------------------------\n");
        sb.append("Total Approved Transactions: ").append(count).append("\n");
        sb.append(String.format("Total Sales Volume: PHP %,.2f\n", totalSales));
        return sb.toString();
    }

    public static boolean exportToTXT(String content, User user) {
        String fileName = getDynamicFileName(user, ".txt");
        String filePath = getDownloadsPath(fileName);
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(content);
            return true;
        } catch (IOException e) { 
            System.err.println("TXT Export Error: " + e.getMessage());
            return false; 
        }
    }

    public static boolean exportToPDF(String content, User user) {
        String fileName = getDynamicFileName(user, ".pdf");
        String filePath = getDownloadsPath(fileName);
        try {
            PdfWriter writer = new PdfWriter(filePath);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);
            document.add(new Paragraph(content));
            document.close();
            return true;
        } catch (Exception e) {
            System.err.println("PDF Export Error: " + e.getMessage());
            return false;
        }
    }

    public static boolean exportToCSV(List<SaleTransaction> transactions, User user) {
        String fileName = getDynamicFileName(user, ".csv");
        String filePath = getDownloadsPath(fileName);
        try (FileWriter writer = new FileWriter(filePath)) {
            // Appended Agent Name header
            writer.write("Transaction ID,Date,Lot ID,Agent Name,Agent ID,Buyer Name,Buyer ID,Financing Type,Amount\n");
            
            for (SaleTransaction t : transactions) {
                boolean isAuthorized = (user instanceof Admin) || (user instanceof Agent && t.getAgentID() == user.getId());

                if (isAuthorized && t.getStatus().equals("Approved")) {
                    Buyer buyer = (Buyer) UserManager.getInstance().getUserById(t.getBuyerID(), "Buyer");
                    String buyerName = (buyer != null) ? buyer.getFirstName() + " " + buyer.getLastName() : "Unknown Buyer";
                    
                    Agent agent = (Agent) UserManager.getInstance().getUserById(t.getAgentID(), "Agent");
                    String agentName = (agent != null) ? agent.getFirstName() + " " + agent.getLastName() : "Unknown Agent";
                    
                    // Included Agent variable injection
                    writer.write(String.format("%d,%s,%d,%s,%d,%s,%d,%s,%.2f\n",
                        t.getTransactionID(), t.getDate(), t.getLotID(), agentName, t.getAgentID(), buyerName, 
                        t.getBuyerID(), t.getFinancingType(), t.getAmount()));
                }
            }
            return true;
        } catch (IOException e) {
            System.err.println("CSV Export Error: " + e.getMessage());
            return false;
        }
    }
}