/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Color;

/**
 *
 * @author xor
 */
public class AgentAssignment extends javax.swing.JDialog {

    
    Color clickedcolor, entered, normal;
    /**
     * Creates new form LotDetailsDialog
     */
    
    // 1. Add these variables at the top of the class
    private String fName, lName, email, password;

    // 2. Replace the default constructor with this one
    public AgentAssignment(java.awt.Frame parent, boolean modal, String fName, String lName, String email, String password) {
        super(parent, modal);
        this.fName = fName;
        this.lName = lName;
        this.email = email;
        this.password = password;
        initComponents();
    }
    
    private void registerWithBlock(int blockNumber) {
        boolean success = controller.UserManager.getInstance().registerAgent(fName, lName, email, password, blockNumber);
        
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Account Created! You are assigned to Block " + blockNumber);
            new StaffLoginFrame().setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Email already exists!", "Registration Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            new RegisterAccountFrame().setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgentAssignment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        block1 = new javax.swing.JButton();
        block2 = new javax.swing.JButton();
        block3 = new javax.swing.JButton();
        block4 = new javax.swing.JButton();
        block5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));

        AgentAssignment.setBackground(new java.awt.Color(30, 30, 30));
        AgentAssignment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        AgentAssignment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select your Assigned Block");
        AgentAssignment.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 439, -1));

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        block1.setBackground(new java.awt.Color(102, 153, 0));
        block1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        block1.setForeground(new java.awt.Color(255, 255, 255));
        block1.setText("Block 1");
        block1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                block1ActionPerformed(evt);
            }
        });
        jPanel1.add(block1);

        block2.setBackground(new java.awt.Color(102, 153, 0));
        block2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        block2.setForeground(new java.awt.Color(255, 255, 255));
        block2.setText("Block 2");
        block2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                block2ActionPerformed(evt);
            }
        });
        jPanel1.add(block2);

        block3.setBackground(new java.awt.Color(102, 153, 0));
        block3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        block3.setForeground(new java.awt.Color(255, 255, 255));
        block3.setText("Block 3");
        block3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                block3ActionPerformed(evt);
            }
        });
        jPanel1.add(block3);

        block4.setBackground(new java.awt.Color(102, 153, 0));
        block4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        block4.setForeground(new java.awt.Color(255, 255, 255));
        block4.setText("Block 4");
        block4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                block4ActionPerformed(evt);
            }
        });
        jPanel1.add(block4);

        block5.setBackground(new java.awt.Color(102, 153, 0));
        block5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        block5.setForeground(new java.awt.Color(255, 255, 255));
        block5.setText("Block 5");
        block5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                block5ActionPerformed(evt);
            }
        });
        jPanel1.add(block5);

        AgentAssignment.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 108, 427, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgentAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgentAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void block1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_block1ActionPerformed
        // TODO add your handling code here:
        registerWithBlock(1);
    }//GEN-LAST:event_block1ActionPerformed

    private void block2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_block2ActionPerformed
        // TODO add your handling code here:
        registerWithBlock(2);
    }//GEN-LAST:event_block2ActionPerformed

    private void block3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_block3ActionPerformed
        // TODO add your handling code here:
        registerWithBlock(3);
    }//GEN-LAST:event_block3ActionPerformed

    private void block4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_block4ActionPerformed
        // TODO add your handling code here:
        registerWithBlock(4);
    }//GEN-LAST:event_block4ActionPerformed

    private void block5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_block5ActionPerformed
        // TODO add your handling code here:
        registerWithBlock(5);
    }//GEN-LAST:event_block5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgentAssignment;
    private javax.swing.JButton block1;
    private javax.swing.JButton block2;
    private javax.swing.JButton block3;
    private javax.swing.JButton block4;
    private javax.swing.JButton block5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
