/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author xor
 */
public class AgentLoginFrame extends javax.swing.JFrame {
    
     /**
     * Creates new form BuyerLoginFrame
     */ 
    private String[] imgslides={"/img/bgimg1.png","/img/bgimg2.png","/img/bgimg3.png"};
    private int imageIndex = 0;
    
   private void imageSlideshow() {

    Timer timer = new Timer(8000, e -> {
        imageIndex = (imageIndex + 1) % imgslides.length;

        bgimg.setIcon(
            new ImageIcon(getClass().getResource(imgslides[imageIndex])));
    });
    timer.start();
}

    public AgentLoginFrame() {
        initComponents();
        imageSlideshow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupName = new javax.swing.JLabel();
        LoginForm = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        Code = new javax.swing.JLabel();
        codePass = new javax.swing.JPasswordField();
        noaccount = new javax.swing.JLabel();
        shiftForms = new javax.swing.JButton();
        login = new javax.swing.JButton();
        switchAccount = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1279, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GroupName.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        GroupName.setForeground(new java.awt.Color(255, 255, 255));
        GroupName.setText("Paul's Group");
        getContentPane().add(GroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 35, 524, 30));

        LoginForm.setBackground(new java.awt.Color(30, 30, 30));
        LoginForm.setFocusable(false);
        LoginForm.setMaximumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setMinimumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setPreferredSize(new java.awt.Dimension(1280, 92));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("<html>Welcome, Agent!</html>");
        Title.setToolTipText("");
        LoginForm.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        Username.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        LoginForm.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, -1, -1));

        userName.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userName.setText("test");
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        LoginForm.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 320, 40));

        Password.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        LoginForm.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        userPass.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        userPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userPass.setText("jPasswordField1");
        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });
        LoginForm.add(userPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 320, 40));

        Code.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Code.setForeground(new java.awt.Color(255, 255, 255));
        Code.setText("Code");
        LoginForm.add(Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 265, -1, -1));

        codePass.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        codePass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        codePass.setText("jPasswordField1");
        codePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codePassActionPerformed(evt);
            }
        });
        LoginForm.add(codePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, 320, 40));

        noaccount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        noaccount.setForeground(new java.awt.Color(255, 255, 255));
        noaccount.setText("Don't have an account?");
        LoginForm.add(noaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        shiftForms.setFont(new java.awt.Font("New Peninim MT", 0, 10)); // NOI18N
        shiftForms.setText("Register");
        shiftForms.setAlignmentY(0.0F);
        shiftForms.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        shiftForms.setBorderPainted(false);
        shiftForms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shiftForms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shiftForms.setMargin(new java.awt.Insets(14, 14, 14, 14));
        shiftForms.setOpaque(true);
        shiftForms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftFormsActionPerformed(evt);
            }
        });
        LoginForm.add(shiftForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 405, 80, 20));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setAlignmentY(0.0F);
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setFocusPainted(false);
        login.setFocusable(false);
        login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.setIconTextGap(0);
        login.setMargin(new java.awt.Insets(14, 14, 14, 14));
        login.setSelected(true);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        LoginForm.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, 40));

        switchAccount.setBackground(new java.awt.Color(102, 102, 102));
        switchAccount.setFont(new java.awt.Font("New Peninim MT", 1, 10)); // NOI18N
        switchAccount.setForeground(new java.awt.Color(255, 255, 255));
        switchAccount.setText("Switch to Buyer's Account");
        switchAccount.setAlignmentY(0.0F);
        switchAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        switchAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        switchAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchAccount.setMargin(new java.awt.Insets(14, 14, 14, 14));
        switchAccount.setOpaque(true);
        switchAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchAccountActionPerformed(evt);
            }
        });
        LoginForm.add(switchAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 340, 20));

        getContentPane().add(LoginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 162, 401, 474));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 92));

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>R E A L<br>E S T A T E<br>M A N A G E R</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 233, 524, 288));

        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main_bg.png"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        AgentDashboard AgentDashboard=new AgentDashboard();
        AgentDashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void shiftFormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftFormsActionPerformed
        // TODO add your handling code here:
        NewAgentAccountFrame NewAgentAccountFrame=new NewAgentAccountFrame();
        NewAgentAccountFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_shiftFormsActionPerformed

    private void codePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codePassActionPerformed

    private void switchAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchAccountActionPerformed
        // TODO add your handling code here:
        BuyerLoginFrame BuyerLoginFrame=new BuyerLoginFrame();
        BuyerLoginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_switchAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Code;
    private javax.swing.JLabel GroupName;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel bgimg;
    private javax.swing.JPasswordField codePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel noaccount;
    private javax.swing.JButton shiftForms;
    private javax.swing.JButton switchAccount;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPass;
    // End of variables declaration//GEN-END:variables
}
