/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Color;

/**
 *
 * @author xor
 */
public class LoginDialog extends javax.swing.JDialog {

    
    Color clickedcolor, entered, normal;
    /**
     * Creates new form LotDetailsDialog
     */
    
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        clickedcolor = new Color(0,0,0);
        entered = new Color(110, 110, 110);
        normal = new Color(255,255,255);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ActionButton2 = new javax.swing.JButton();
        ActionButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));

        LoginDetails.setBackground(new java.awt.Color(30, 30, 30));
        LoginDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("How do you want so login as?");

        ActionButton2.setBackground(new java.awt.Color(0, 153, 0));
        ActionButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ActionButton2.setForeground(new java.awt.Color(255, 255, 255));
        ActionButton2.setText("Login as a Buyer");
        ActionButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActionButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActionButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActionButton2MouseExited(evt);
            }
        });
        ActionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButton2ActionPerformed(evt);
            }
        });

        ActionButton3.setBackground(new java.awt.Color(255, 98, 96));
        ActionButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ActionButton3.setForeground(new java.awt.Color(255, 255, 255));
        ActionButton3.setText("Login as an Agent");
        ActionButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActionButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActionButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActionButton3MouseExited(evt);
            }
        });
        ActionButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginDetailsLayout = new javax.swing.GroupLayout(LoginDetails);
        LoginDetails.setLayout(LoginDetailsLayout);
        LoginDetailsLayout.setHorizontalGroup(
            LoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginDetailsLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(ActionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ActionButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        LoginDetailsLayout.setVerticalGroup(
            LoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDetailsLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ActionButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButton3ActionPerformed
        // TODO add your handling code here:
        AgentLoginFrame AgentLoginFrame=new AgentLoginFrame();
        AgentLoginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ActionButton3ActionPerformed

    private void ActionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButton2ActionPerformed
        // TODO add your handling code here:
        BuyerLoginFrame BuyerLoginFrame=new BuyerLoginFrame();
        BuyerLoginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ActionButton2ActionPerformed

    private void ActionButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActionButton2MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_ActionButton2MouseClicked

    private void ActionButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActionButton2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_ActionButton2MouseEntered

    private void ActionButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActionButton2MouseExited
        // TODO add your handling code here:
   
    }//GEN-LAST:event_ActionButton2MouseExited

    private void ActionButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActionButton3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ActionButton3MouseClicked

    private void ActionButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActionButton3MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_ActionButton3MouseEntered

    private void ActionButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActionButton3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ActionButton3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionButton2;
    private javax.swing.JButton ActionButton3;
    private javax.swing.JPanel LoginDetails;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
