/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

/**
 *
 * @author xor
 */
public class LotDetailsDialog extends javax.swing.JDialog {

    /**
     * Creates new form LotDetailsDialog
     */
    public LotDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LotDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Info1 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        ActionButton1 = new javax.swing.JButton();
        ActionButton2 = new javax.swing.JButton();
        ActionButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));

        LotDetails.setBackground(new java.awt.Color(30, 30, 30));
        LotDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("L O T  D E T A I L S");

        Info1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Info1.setForeground(new java.awt.Color(255, 255, 255));
        Info1.setText("Enter Lot Information");

        Info2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Info2.setForeground(new java.awt.Color(255, 255, 255));
        Info2.setText("Enter Lot Information");

        Info3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Info3.setForeground(new java.awt.Color(255, 255, 255));
        Info3.setText("Enter Lot Information");

        ActionButton1.setBackground(new java.awt.Color(0, 78, 122));
        ActionButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ActionButton1.setForeground(new java.awt.Color(255, 255, 255));
        ActionButton1.setText("Reserve");

        ActionButton2.setBackground(new java.awt.Color(0, 153, 0));
        ActionButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ActionButton2.setForeground(new java.awt.Color(255, 255, 255));
        ActionButton2.setText("Buy");
        ActionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButton2ActionPerformed(evt);
            }
        });

        ActionButton3.setBackground(new java.awt.Color(255, 98, 96));
        ActionButton3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ActionButton3.setForeground(new java.awt.Color(255, 255, 255));
        ActionButton3.setText("Sell");
        ActionButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LotDetailsLayout = new javax.swing.GroupLayout(LotDetails);
        LotDetails.setLayout(LotDetailsLayout);
        LotDetailsLayout.setHorizontalGroup(
            LotDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LotDetailsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(LotDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LotDetailsLayout.createSequentialGroup()
                        .addComponent(ActionButton3)
                        .addGap(69, 69, 69)
                        .addComponent(ActionButton2))
                    .addGroup(LotDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Info3)
                        .addComponent(Info2)
                        .addComponent(Info1)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(ActionButton1)
                .addGap(17, 17, 17))
        );
        LotDetailsLayout.setVerticalGroup(
            LotDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LotDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Info1)
                .addGap(8, 8, 8)
                .addComponent(Info2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Info3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(LotDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActionButton1)
                    .addComponent(ActionButton2)
                    .addComponent(ActionButton3))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LotDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LotDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActionButton2ActionPerformed

    private void ActionButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActionButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LotDetailsDialog dialog = new LotDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionButton1;
    private javax.swing.JButton ActionButton2;
    private javax.swing.JButton ActionButton3;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JPanel LotDetails;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
