/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author xor
 */
public class NewBuyerAccountFrame extends javax.swing.JFrame {
    
     /**
     * Creates new form BuyerLoginFrame
     */ 
    private String[] imgslides={"/img/bgimg1.png","/img/bgimg2.png","/img/bgimg3.png"};
    private int imageIndex = 0;
    
   private void imageSlideshow() {

    Timer timer = new Timer(8000, e -> {
        imageIndex = (imageIndex + 1) % imgslides.length;

        bgimg.setIcon(
            new ImageIcon(getClass().getResource(imgslides[imageIndex])));
    });
    timer.start();
}

    public NewBuyerAccountFrame() {
        initComponents();
        imageSlideshow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupName = new javax.swing.JLabel();
        LoginForm = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        noaccount = new javax.swing.JLabel();
        shiftForms = new javax.swing.JButton();
        switchAccount = new javax.swing.JButton();
        userPass1 = new javax.swing.JPasswordField();
        Password1 = new javax.swing.JLabel();
        buyerEmailField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1279, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GroupName.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        GroupName.setForeground(new java.awt.Color(255, 255, 255));
        GroupName.setText("Paul's Group");
        getContentPane().add(GroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 35, 524, 30));

        LoginForm.setBackground(new java.awt.Color(30, 30, 30));
        LoginForm.setFocusable(false);
        LoginForm.setMaximumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setMinimumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setPreferredSize(new java.awt.Dimension(1280, 92));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("<html>Create a Buyer's Account</html>");
        Title.setToolTipText("");
        LoginForm.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, -1));

        FirstName.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");
        LoginForm.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        firstName.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        firstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstName.setText("test");
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        LoginForm.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 40));

        LastName.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");
        LoginForm.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lastName.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        lastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastName.setText("test");
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        LoginForm.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 320, 40));

        Password.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Email");
        LoginForm.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Sign Up");
        login.setAlignmentY(0.0F);
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.setMargin(new java.awt.Insets(14, 14, 14, 14));
        login.setOpaque(true);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        LoginForm.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 300, 40));

        noaccount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        noaccount.setForeground(new java.awt.Color(255, 255, 255));
        noaccount.setText("Already have an account?");
        LoginForm.add(noaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        shiftForms.setFont(new java.awt.Font("New Peninim MT", 0, 10)); // NOI18N
        shiftForms.setText("Login");
        shiftForms.setAlignmentY(0.0F);
        shiftForms.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        shiftForms.setBorderPainted(false);
        shiftForms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shiftForms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shiftForms.setMargin(new java.awt.Insets(14, 14, 14, 14));
        shiftForms.setOpaque(true);
        shiftForms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftFormsActionPerformed(evt);
            }
        });
        LoginForm.add(shiftForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 80, 20));

        switchAccount.setBackground(new java.awt.Color(102, 102, 102));
        switchAccount.setFont(new java.awt.Font("New Peninim MT", 1, 10)); // NOI18N
        switchAccount.setForeground(new java.awt.Color(255, 255, 255));
        switchAccount.setText("Switch to Buyer's Account");
        switchAccount.setAlignmentY(0.0F);
        switchAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        switchAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        switchAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchAccount.setMargin(new java.awt.Insets(14, 14, 14, 14));
        switchAccount.setOpaque(true);
        switchAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchAccountActionPerformed(evt);
            }
        });
        LoginForm.add(switchAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 340, 20));

        userPass1.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        userPass1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userPass1.setText("jPasswordField1");
        userPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPass1ActionPerformed(evt);
            }
        });
        LoginForm.add(userPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 320, 40));

        Password1.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Password1.setForeground(new java.awt.Color(255, 255, 255));
        Password1.setText("Password");
        LoginForm.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        buyerEmailField.setText("testemail@test.com");
        buyerEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerEmailFieldActionPerformed(evt);
            }
        });
        LoginForm.add(buyerEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, 40));

        getContentPane().add(LoginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 132, 401, 540));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 92));

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>R E A L<br>E S T A T E<br>M A N A G E R</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 233, 524, 288));

        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main_bg.png"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String fName = firstName.getText();
        String lName = lastName.getText();
        String email = buyerEmailField.getText(); // Ensure this matches your variable name
        String password = new String(userPass1.getPassword());

        if (fName.isEmpty() || lName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        boolean success = controller.UserManager.getInstance().registerBuyer(fName, lName, email, password);
        
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Buyer Account Created! Please Login.");
            new BuyerLoginFrame().setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Email already exists!", "Registration Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void shiftFormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftFormsActionPerformed
        // TODO add your handling code here:
        BuyerLoginFrame BuyerLoginFrame=new BuyerLoginFrame();
        BuyerLoginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_shiftFormsActionPerformed

    private void switchAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchAccountActionPerformed
        // TODO add your handling code here:
        BuyerLoginFrame BuyerLoginFrame=new BuyerLoginFrame();
        BuyerLoginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_switchAccountActionPerformed

    private void userPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPass1ActionPerformed

    private void buyerEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyerEmailFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBuyerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBuyerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBuyerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBuyerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBuyerAccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel GroupName;
    private javax.swing.JLabel LastName;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel bgimg;
    private javax.swing.JTextField buyerEmailField;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton login;
    private javax.swing.JLabel noaccount;
    private javax.swing.JButton shiftForms;
    private javax.swing.JButton switchAccount;
    private javax.swing.JPasswordField userPass1;
    // End of variables declaration//GEN-END:variables
}
